### ISSUE TITLE
[NIF prov] new concept: nif:AnnotationUnit

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#110]

**Comment by neradis** [comment]
Instances of`nif:AnnotationUnit` associate `nif:String` instances with annotation statements together with confidence and/or provenance information. As detailed in  the [NIF 2.1 RC Docs](http://nif.readthedocs.org/en/2.1-rc/prov-and-conf.html) specialised *companion properties* can be used to state confidence and/or provenance, or one can use the generic `nif:provenenanace` and `nif:confidence` properties.

#### When *companion properties are used:

`nif:AnnotationUnit` resources are only introduced for an annotated string `s` if there is more than one piece of annotation information that should have associated confidence/provenance information to be expressed with the same *companion properties*. For an example, consider the string `ex:doc_offset_0_5` (*"Apple"*) in https://raw.githubusercontent.com/NLP2RDF/documentation/2.1-RC/docs/includes/nif21-acquisition-companion-properties.ttl . Concerning entity linking, there are two pieces of annotation information
```
ex:doc_offset_0_5 itsrdf:taIdentRef dbp:Apple_Inc .
ex:doc_offset_0_5 itsrdf:taIdentRef dbp:Apple_Bank_for_Savings .
```
that share the same *confidence companion property*, `nif:taIdentConf`. Thus an annotation unit was introduced (line 35 to 42), for the less likely entity link for the financial institution:
```
nif:annotationUnit [
    itsrdf:taIdentRef dbp:Apple_Bank_for_Savings ;
    nif:taIdentConf "0.3"^^xsd:decimal ;
    nif:taIdentProv freme-api:description%2Fe-entity%2Fdbpedia-spotlight%2Fdocuments ;
    # [...] (possibly more annotation with conf./prov. info using other compation prop. here...
 ] .
```


#### When using the generic properties:
For each piece of annotation information with confidence or provenance information (or both) a seperate annotation unit is introduced grouping the annoation assertion to its confidence/provenance meta-statements. See https://raw.githubusercontent.com/NLP2RDF/documentation/2.1-RC/docs/includes/nif21-acquisition-generic-properties.ttl for an example

**Comment by jnehring** [comment]
I have several thoughts about annotationUnit. They contradict each other so please consider them one by one and not as all together as one concept.

* It breaks existing tooling so I do not like the idea in general. We will have to reprogram many clients, even if they do not use confidence or provenance information, because the structure of the annotations changes.
* I do not see why we need both generic properties and annotationUnits. What is the benefit of having two different ways to describe annotations? So I suggest to use only annotationUnit and drop the generic properties.
* I would name it "annotation" instead of "annotationUnit". This is simpler. Or does the word "unit" carry any important semantic?
* One idea to replace annotationUnit with more downward compatiblity: Changing the URIs of annotations. Right now an annotation has URI http://example.org/nif-21/acq#doc_offset_10_15. When there are two annotation units for this annotation, we could give them the URIs http://example.org/nif-21/acq#doc_offset_10_15-1 and http://example.org/nif-21/acq#doc_offset_10_15-2

**Comment by jnehring** [comment]
this discussion is over
