### ISSUE TITLE
Private keys for each e-service

### ISSUE THREAD

**Issue by andish** [freme-project/technical-discussion#61]
To access user's private date on each e-service (at least for e-Terminology and e-translation) it is needed somehow to allow the user be identified in e-service.

From developers call minutes:
2 possible solutions:
   1) Introduce new parameters like tilde-user, tilde-pw -> 2 credentials needed: for FREME and for Tilde. Then users need to attach tw
   2) Credential store to upload credentials to. Then you can use the credentials you like. Then users do not need to attach different credentials to one call.

**Comment by andish** [comment]
User key for each Tilde e-service looks like this: 6e3a3d52-f595-4ba1-8aaf-cc67bb825b11.

**Comment by ghsnd** [comment]
Now a `User` has a name, password, role and can have one or more tokens. Isn't it possible to add a (key, value) Map as member in the `User` class that can contain extra data for a given service or company, for instance

    Tilde -> 6e3a3d52-f595-4ba1-8aaf-cc67bb825b11

Then the `UserController` allows the services e-Translate and e-Terminology to get the data mapped to the *Tilde* key. Then e-Translate / e-Terminology gets this data the Tilde user key) and knows that it is a Tilde user.

**Comment by ghsnd** [comment]
Or since each Tilde service has another key, it can also be, e.g.,

    e-Terminology -> 6e3a3d52-f595-4ba1-8aaf-cc67bb825b11
    e-Translate -> 7f3a3d52-f595-4ba1-6aff-cc67bb825b15

**Comment by jnehring** [comment]
@ghsnd I think your suggestions refer to solution 2. I share your opinion that this is a good way to implement such a service

I am also thinking from the user perspective. I think the user wants the system to be easy and secure. 

Option 1) is very easy and straight forward for users who want to use a Tilde API key. But it introduces additional complexity to users who don't use a Tilde API key because it introduces two additional parameters to both Tilde endpoints. Two parameters because we want to be able to send the token via header (more secure) and via query string (more convenient). Option 2 makes it more complex for users who want to use a custom Tilde API key. I expect more people to not use a custom Tilde API key. Also with Option 2) we can have the same solution for all e-Services. So I think Option 2 is easier.

Option 1 is more secure because the API keys which are sensitive data are not stored in FREME. Option 2 introduces the possibility of stealing API keys through breaking into FREME. But I think that even when using Option 1 a hacker might be able to sniff the Tilde API keys through breaking into FREME so Option 1 adds potential risk for sensitive user data also.

I have the feeling that option 2) might be better then option 1) but this is opinion is not very strong.

**Comment by jnehring** [comment]
We have implemented solution 1
