### ISSUE TITLE
[critical] FREME does not compile at Jenkins

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#73]
FREME does not compile at Jenkins. In particular, FREMECommon and pipelines fail.

**Comment by jnehring** [comment]
The builds are unstable. Failed is another, worse state. But this is only splitting hairs about terminology, we should fix the unstable builds.

The problem in FREME common is a failed unit test. There is already a GitHub issue: https://github.com/freme-project/FREMECommon/issues/6

The problem with pipelines is also a failed unit test. I created a GitHub issue:
https://github.com/freme-project/pipelines/issues/19

I close this issue because these two issues cover it.
