### ISSUE TITLE
hosting of linked-data-fragments artifact in our repo

### ISSUE THREAD

**Issue by m1ci** [freme-project/technical-discussion#74]
For e-link we need the LDF java client artifact
https://github.com/LinkedDataFragments/Client.Java
Unfortunately, the artifact is not present in any maven repository.

What about hosting it in our FREME repo?
@jnehring What do you think? if yes, can you please do the setup?
Thanks!

**Comment by jnehring** [comment]
I will produce the artifact and upload it to our maven repo.

**Comment by m1ci** [comment]
Great, thanks! let us know when this is ready.

**Comment by jnehring** [comment]
I uploaded the artifact to our maven repo: http://rv1443.1blu.de/nexus/content/repositories/releases/org/linkeddatafragments/ldf-client/0.1/

The group id is `org.linkeddatafragments`, artifact id `ldf-client` and version `0.1`.

This is a temporary solution: When FREME project life time ends and we shut down the server containing our maven repo then it will no longer be possible to compile e-link. Because this artifact is no longer available. So my prefered solution would be to ask the author of linked data java client to upload it to maven central - @m1ci already asked Ruben. The other solution would be to directly include the source code of the java ldf client into our project. The later introduces some other problems so lets hope the artifact will be uploaded to maven central.
