### ISSUE TITLE
SDK's Good idea?

### ISSUE THREAD

**Issue by xFran** [freme-project/technical-discussion#75]
I'm 100% agree with making documentation, tutorials and so on. From the developers (API consumers) point of view they want to see the results in the desired format. They want to follow KISS programming principle. They don't care about what is happening behind scenes. 
Do you care when you build an application and you're using Google's API? Honestly I don't.

After all any researcher needs a software developer to use the API at the highest level and extract all the benefits. I believe having SDK's for common programming languages used to build web applications (PHP, Java, Python) helps developers to consume of FREME API's in the correct way, using the correct URL, TESTING, REPRODUCE ERRORS etcetera. We all know the problems, enough to browse all opened and closed issues.

If I'm not the only one who thinks having SDK's is good for FREME/end user's/business partners maybe we should talk about.

**Comment by fsasaki** [comment]
Hi Francisc,

FREME others services. The services are accessible via APIs or GUIs. So a
user needs documentation about APIs or GUIs.
I see the type of documentation we need at the end like a user guide. See
e.g. the MS translation hub documentation
https://hub.microsofttranslator.com/Help/Download/Microsoft%20Translator%20Hub%20User%20Guide.pdf
I agree, showing how to use FREME in certain programing language is of
great value too. I see also the BC partners as the creators of such SDKs.
E.g. from my understanding Wripl is using FREME from php, vistatec from
java etc. Do you think Wripl would like to make a start with an SKD for php?

2015-10-07 15:20 GMT+02:00 Francisc <notifications@github.com>:

**Comment by xFran** [comment]
Hi Felix, 

Sure. Why not? I mean Wripl is one of the big FREME's API consumer is kinda our obligation. With Jan, Milan and your support and collaboration I can do it for PHP. 
If this is going well, no promises but I will try to make a SDK for Python also as a personal project since in Wripl we don't need it. In this way we will encourage more software  developers to use and get closer of FREME very important now as Open Source Project. 

Definitely we need documentation too. MS translation hub documentation it's a good how to do example. 

Let's start discussing about the benefits and inconveniences of using SDK,  incorporate others people ideas and do it properly. I just pointed some benefits. Maybe is not useful enough to spend time on it. 

I leave it in your hands.

**Comment by fsasaki** [comment]
Oh no, please don't leave it in my hands :) if you want to start with one programing language (python, php, ...) that would be nice. I just would not push others to start with this since it is BC partners who work with their selected programming languages. And the success of FREME at the moment depends on showing its usefulness in the BC partner applications, so I see why BC partner focus on that.

**Comment by jnehring** [comment]
I think it is a lot of work to create an SDK for one programming language. Right now FREME has 22 API methods and an extensive SDK would have to support all these methods. Also it needs to provide documentation for these 22 methods. And quality assurance through unit tests and manual tests. Also it requires constant updates as the FREME API develops. I think SDKs would be really useful, but in FREME we do not have the resources to create them. Right now we have to put our focus on FREME core, which is the REST API and the underlying enrichments.

I also have other tasks in my mind for WRIPL programmers which I find more urgent right now (not all in FREME 0.4): Topic detection, big data testing, assistance to setup monitoring.

But I do not want to discourage the development of SDKs. I think an SDK is especially useful for the topic detection because the step from the output of FREME NER to extracting the top n DBPedia categories is not trivial. So when WRIPL has a working script for that, sharing and documenting this code would be IMO a good starter for such SDK.

> With Jan, Milan and your support and collaboration I can do it for PHP. 

Nice. I am happy to support you. Im interested what @koidl says to that.

> If this is going well, no promises but I will try to make a SDK for Python also as a personal project since in Wripl we don't need it.

This is very nice. Also here I am happy to support you.

**Comment by xFran** [comment]
I wrote a ZF2 module to consume FREME NER heavily customised for Wripl needs (e-Entity only for the moment and json+ld  as response content type) so useless for anybody else even if I share the script that's why I came up with the SDK idea. 

> Right now FREME has 22 API methods and an extensive SDK would have to support all these methods.
> Topic detection. 

Good. We don't have to make one SDK to rule them all (even if I like the ideea is not very good practice :) )  We can start with e-Entity service.

Now, for what I will need assistance and support is play with the SDK which means:

- you have to set up an environment for this
- manually test it
- see the content see the response and compare it with other environments
- check for differences
- investigate why the response is different  for another
- which is the best approach 
- feedback
- advise/explain (keep in mind that the software developers in most of the cases are not researchers and not living manuals either and this can annoy researchers  :). Just teasing you.)
... a few more.

It is a lot of work you're right @jnehring. I don't want to spend time on this because Wripl is not using all 22 services if I don't have support. Not because you guys don't want to help but because of lack of time I understand and I'm aware.  Like the rest of us you must understand and be aware.  

Any thoughts? Or, we consider this for the future?

**Comment by fsasaki** [comment]
Hi @xFran , yes, consider this for the future. At the moment the BC partner need to focus on making their usage of FREME useful for themselves, so that FREME is useful for their end customers. In this process I don't see a BC partner asking for an SDK. SDK seems to be valuable though for getting third party adoption, so we should come back to this indeed.
