### ISSUE TITLE
Cleaning content

### ISSUE THREAD

**Issue by xFran** [freme-project/technical-discussion#90]
I'm trying to clean this content 
[freme.txt](https://github.com/freme-project/technical-discussion/files/38018/freme.txt)

What I did is:
- Remove html tags
- Remove newlines
- Remove duplicate words
- Remove words with less than 3 characters (here I should use a stop words list)

and the result is this nice and clean words list separated by one space:
```
UPDATED MONDAY Novemberua affiliated with leagues cover totally independent media company also other Ireland will expanding indepth coverage those soon Senior Sunday Team Crumlin United Mochtas Drumcondra Bluebell Malahide Firhouse Clover Killester Glebe North Patricks CYFC Home Farm Tolka Rovers Greystones Glenville nbsp Dunboyne Bangor Celtic Cherry Orchard Wayside Arklow Town Verona Dublin Francis Leixlip Swords Broadford Sacred Heart University Premier Points Collinstown Sheriff East Wall Bessborough Sandyhill Shangan Kevins Boys Baldoyle Grange Finglas Kilbarrack Ayrfield Trinity Donaghmede ODevaney Dunard Pauls Artane Rivervalley Rangers Darndale Usher Transylvania Real Transilvania Castleknock Valley Park Hardwicke Brendans Dingle Ashbourne Raheny McKelvey Balscadden Pats Phoenix Oatfield Howth Wyteleaf White Eagles Carndonagh Malachys Edenmore Newtown Villa Limerick Division Carew Geraldines Pike Fairview Janesboro Regional Aisling Annacotty Ballynanty Moyross Summerville Mungret Wembley TSDL Played Drew Lost Michaels Clonmel Cashel Peake Bridge Glengoole Bansha Mile Borris Kilkenny District Leagueua Drawn Goals Against Goal Diff Thomastown Callan Evergreen Freebooters Newpark Stoneyford Lions Freshford Mayo Super League Westport Ballina Castlebar Ballyheane Manulla Ballyglass Iorras Aonthaithe Conn Charlestown Straide Foxford relegated Westport Champions Runners
```

__Questions:__

How this will influence spotting entities and terms? This is good or is bad? This makes any sense?

Thanks in advance.

**Comment by jnehring** [comment]
* Remove html tags - can be a good idea. Actually e-Internationalization should be able to do so also.
* Remove newlines - I do not see any benefit from this
* Remove duplicate words, Remove words with less than 3 characters, Stopword list - I would advise not to remove these words before sending it to FREME. FREME NER needs the sentences to be as natural and clean as possible. When you delete words from them the sentences are less clean and therefore the quality of FREME NER will become worse. So I propose to do this cleaning after you got the results from FREME

It seems you also delete dots. I advise not to delete the dots because they are also interpreted by FREME NER.

**Comment by xFran** [comment]
Ok. So,  going to extreme cleaning is not good idea either. :)  Good to know. Thank you. Jan.
